import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner"
import { KarmaThemeProvider } from "@/components/karmaThemeProvider";
import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata = {
    title: "KarmaGate || Advanced Antibot Protection",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <ClerkProvider>
            <html lang="en" data-scroll-behavior="smooth" suppressHydrationWarning>
                <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                    <KarmaThemeProvider
                        attribute="class"
                        defaultTheme="dark"
                        enableSystem
                    >
                        {children}
                    </KarmaThemeProvider>
                    <Toaster richColors position="top-right" />
                </body>
            </html>
        </ClerkProvider>
    );
}
